name: Sniff

on: pull_request

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup PHP with Composer
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: composer

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install theme dependencies
              run: composer install

            - name: Install dependencies
              run: composer install

            - name: Run PHPCS
              run: composer run sniff
